/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TechnicalOfficer;

import java.sql.Connection;
import java.sql.PreparedStatement;
import Admin.forms_Login;

/**
 *
 * @author Umayanga
 */
public class DeanLogin extends javax.swing.JFrame {

    /**
     * Creates new form DeanLogin
     */
    public DeanLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        dean = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        id2 = new javax.swing.JTextField();
        password2 = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        back = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dean");
        setResizable(false);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Adobe Caslon Pro", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Dean");
        panel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        dean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TechnicalOfficer/dean.png"))); // NOI18N
        panel.add(dean, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 150, 150));

        id.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("ID");
        panel.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        password.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");
        panel.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));
        panel.add(id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 260, 30));
        panel.add(password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 260, 30));

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        panel.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 150, 40));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TechnicalOfficer/exit.png"))); // NOI18N
        back.setPreferredSize(new java.awt.Dimension(20, 20));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserLogin(evt);
            }
        });
        panel.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TechnicalOfficer/background.jpg"))); // NOI18N
        panel.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        DeanUpdateProfile update = new DeanUpdateProfile();

        update.setVisible(true);
        this.dispose();
        
        String password=password2.getText().trim();
        String Id=id2.getText().trim();

        if(Id.isEmpty() && password.isEmpty())
        {
            errMsg.setText("Please enter both fields!!!");
        }
        else if(password.isEmpty())
        {
            errMsg.setText("Please enter password!!!");
        }
        else if(Id.isEmpty())
        {
            errMsg.setText("Please enter id!!!");
        }
        else{
            ResultSet rs=null;
            try{
               Connection con = DbConnection.getMyConnection(); //Add connection
                String sql="call users('"+Id+"','"+password+"')";
                PreparedStatement ps=con.prepareStatement(sql);
                rs=(ResultSet) ps.executeQuery();
                if(rs.next()==true)
                {
                    LogTO_1 log=new LogTO_1();
                    log.setId2(rs.getString("Id"));

                    tecLogin inter=new tecLogin();
                    inter.setVisible(true);
                    this.setVisible(false);
                }
                else{
                    errMsg.setText("invalid user");
                }

            }
            catch(Exception e)
            {
                errMsg.setText("system error");
            }
        }
       
    }//GEN-LAST:event_loginActionPerformed

    private void UserLogin(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserLogin
        forms_Login login = new forms_Login();

        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UserLogin

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeanLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeanLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeanLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeanLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeanLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel background;
    private javax.swing.JLabel dean;
    private javax.swing.JLabel id;
    private javax.swing.JTextField id2;
    private javax.swing.JButton login;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel password;
    private javax.swing.JTextField password2;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private static class errMsg {

        private static void setText(String please_enter_both_fields) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public errMsg() {
        }
    }

    private static class ResultSet {

        public ResultSet() {
        }

        private boolean next() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private String getString(String id) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
