/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TechnicalOfficer;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Umayanga
 */
public class tecWelcome extends javax.swing.JFrame {

    /**
     * Creates new form TechnicalOfficer
     */
    public tecWelcome(ResultSet rs ) {
        initComponents();
        LogTO_1 logTO_1 = new LogTO_1();
        try {
            logTO_1.setId2(rs.getString("user_id"));
            //System.out.println(logTO_1.getId2());
        } catch (SQLException ex) {
            Logger.getLogger(tecWelcome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    tecWelcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        attendance = new javax.swing.JLabel();
        medical = new javax.swing.JLabel();
        update = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        attendance2 = new javax.swing.JLabel();
        medical2 = new javax.swing.JLabel();
        update4 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Technical Officer");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TechnicalOfficer/attendance.png"))); // NOI18N
        attendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendanceMouseClicked(evt);
            }
        });
        jPanel1.add(attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 130, 120));

        medical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TechnicalOfficer/medi1.png"))); // NOI18N
        medical.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medicalMouseClicked(evt);
            }
        });
        jPanel1.add(medical, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 130, 130));

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TechnicalOfficer/Update1.png"))); // NOI18N
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 140, 140));

        title.setFont(new java.awt.Font("Adobe Caslon Pro", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Welcome to Technical Officer");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        attendance2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        attendance2.setForeground(new java.awt.Color(255, 255, 255));
        attendance2.setText("Attendance");
        attendance2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendance2MouseClicked(evt);
                tecAttendance(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attendance2MouseEntered(evt);
            }
        });
        jPanel1.add(attendance2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, -1));

        medical2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        medical2.setForeground(new java.awt.Color(255, 255, 255));
        medical2.setText("Medical");
        medical2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tecMedical(evt);
            }
        });
        jPanel1.add(medical2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, -1, -1));

        update4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        update4.setForeground(new java.awt.Color(255, 255, 255));
        update4.setText("Update Profile");
        update4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update4MouseClicked(evt);
                tecUpdateProfile(evt);
            }
        });
        update4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                update4KeyPressed(evt);
            }
        });
        jPanel1.add(update4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TechnicalOfficer/exit.png"))); // NOI18N
        back.setPreferredSize(new java.awt.Dimension(20, 20));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tecLogin(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 50));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TechnicalOfficer/background.jpg"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void update4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_update4MouseClicked

    private void update4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_update4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_update4KeyPressed

    private void tecUpdateProfile(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tecUpdateProfile
        
    }//GEN-LAST:event_tecUpdateProfile

    private void attendance2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendance2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_attendance2MouseClicked

    private void attendance2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendance2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_attendance2MouseEntered

    private void tecAttendance(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tecAttendance
       
    }//GEN-LAST:event_tecAttendance

    private void tecMedical(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tecMedical
        tecMedical medical = new tecMedical();
        
        medical.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tecMedical

    private void tecLogin(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tecLogin
        tecLogin login = new tecLogin();
        
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tecLogin

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
      tecUpdateProfile update = new tecUpdateProfile();
      update.setVisible(true);
      this.dispose();
       
      
        
    }//GEN-LAST:event_updateMouseClicked

    private void attendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseClicked
        tecAttendance attendance = new tecAttendance();
        
        attendance.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_attendanceMouseClicked

    private void medicalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicalMouseClicked
     tecMedical medical = new tecMedical();
        
        medical.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_medicalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tecWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tecWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tecWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tecWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new tecWelcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel attendance;
    private javax.swing.JLabel attendance2;
    private javax.swing.JLabel back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel medical;
    private javax.swing.JLabel medical2;
    private javax.swing.JLabel title;
    private javax.swing.JLabel update;
    private javax.swing.JLabel update4;
    // End of variables declaration//GEN-END:variables
}
