/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TechnicalOfficer;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Umayanga
 */
public class ViewAttendance extends javax.swing.JFrame {

    /**
     * Creates new form ViewAttendance
     */
    public ViewAttendance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        cuid = new javax.swing.JLabel();
        cuid2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        back = new javax.swing.JLabel();
        serach = new javax.swing.JLabel();
        stid2 = new javax.swing.JTextField();
        stid1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Attendance");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Adobe Caslon Pro", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("See Attendance");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        cuid.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cuid.setForeground(new java.awt.Color(255, 255, 255));
        cuid.setText("Course ID");
        jPanel1.add(cuid, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));
        jPanel1.add(cuid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 180, 30));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "stu_id", "cu_id", "day", "type", "hours", "status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 580, 180));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TechnicalOfficer/exit.png"))); // NOI18N
        back.setPreferredSize(new java.awt.Dimension(20, 20));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tecAttendance(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 50));

        serach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serachMouseClicked(evt);
            }
        });
        jPanel1.add(serach, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, -1, -1));

        stid2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stid2MouseClicked(evt);
            }
        });
        stid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stid2ActionPerformed(evt);
            }
        });
        stid2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stid2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stid2KeyTyped(evt);
            }
        });
        jPanel1.add(stid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 180, 30));

        stid1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        stid1.setForeground(new java.awt.Color(255, 255, 255));
        stid1.setText("Student ID");
        jPanel1.add(stid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jButton1.setText("Search");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TechnicalOfficer/background.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 840, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tecAttendance(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tecAttendance
        tecAttendance attendance = new tecAttendance();

        attendance.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_tecAttendance

    private void serachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serachMouseClicked
        String StuId = stid2.getText();
        String SubId = cuid2.getText();

        if (!StuId.equals("") && !SubId.equals("")) {
            try {
                Connection con = DbConnection.getMyConnection(); //Add connection
                String sql = "select `stu_id` AS 'Stu_id', `day` AS 'Day',`type` AS 'Type',`hours` AS 'Hours',`status` AS 'Status' from attendance where stu_id='" + StuId + "' and cu_id='" + SubId + "' ";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));
                table.setVisible(true);

            } catch (Exception e) {
                table.setVisible(false);
            }
        } else {
            table.setVisible(false);
            JOptionPane.showMessageDialog(null, "Please Enter Student ID and Subject ID");
        }
    }//GEN-LAST:event_serachMouseClicked

    private void stid2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stid2MouseClicked

    }//GEN-LAST:event_stid2MouseClicked

    private void stid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stid2ActionPerformed

    }//GEN-LAST:event_stid2ActionPerformed

    private void stid2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stid2KeyTyped

    }//GEN-LAST:event_stid2KeyTyped

    private void stid2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stid2KeyPressed

    }//GEN-LAST:event_stid2KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String StuId = stid2.getText();
        String SubId = cuid2.getText();

        try {
            Connection con = DbConnection.getMyConnection(); //Add connection
            String sql = "select * from attendance where stu_id = '" + StuId + "' ";

            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
//                table.setModel(DbUtils.resultSetToTableModel(rs));

            while (rs.next()) {
              
                DefaultTableModel model = (DefaultTableModel) (table.getModel());
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5),rs.getString(6)});
                System.out.println("here");
            }
        } catch (Exception e) {
//                table.setVisible(false);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel background;
    private javax.swing.JLabel cuid;
    private javax.swing.JTextField cuid2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel serach;
    private javax.swing.JLabel stid1;
    private javax.swing.JTextField stid2;
    private javax.swing.JTable table;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
