/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Student;

import Lecturer.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class st_grade extends javax.swing.JFrame {

    /** Creates new form St_grade */
    public st_grade() {
        initComponents();
         subject();
    }

    
     PreparedStatement pdst;
     DbConnect con=new DbConnect();
     DefaultTableModel tmodel;
   
     St_ca vc=new St_ca();
     
     String stid;
     String sub;
     
     

     double CAtotal;
   st_grade(double catotal) {
      this.CAtotal=catotal;
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        subname = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        gpa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Grade & GPA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 20, 160, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lecturer/back.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(470, 0, 90, 90);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Subject");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 170, 80, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GPA");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(430, 240, 80, 30);
        jPanel1.add(id);
        id.setBounds(150, 100, 170, 40);

        subname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(subname);
        subname.setBounds(150, 160, 170, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lecturer/search.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(340, 140, 50, 30);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Subject Code", "CA MArks", "Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 240, 360, 90);
        jPanel1.add(gpa);
        gpa.setBounds(400, 280, 100, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Student ID");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 110, 80, 30);

        jButton1.setText("clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 360, 61, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lecturer/search.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(524, 290, 40, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lecturer/background.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(-6, 0, 580, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       getmarks(get_text(stid),get_text2(sub));
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      for(int c=tmodel.getRowCount()-1;c>=0;c--){
                            tmodel.removeRow(c);
                        }
         
         //and clear the combo box and txtfield
         id.setText("");
         subname.setSelectedIndex(-1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
     StGrade co = new StGrade();  // back 
        co.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       String grade="";
        String sub="";
        int credit=0;
        double value=0;
        double valuetot=0;
        double tot=0;
        double credittot=0;
        double GPA=0;

        for(int i=0;i<table.getRowCount();i++){
            grade =(String)table.getValueAt(i,3);
            sub =(String)table.getValueAt(i,1);

            switch (sub){
                case "ICT2113":
                credit=3;
                break;

                case "ICT2123":
                credit=3;
                break;

                case "ICT2133":
                credit=3;
                break;

                case "ICT2142":
                credit=2;
                break;

                case "ICT2153":
                credit=2;
                break;

                case "TCS2112":
                credit=2;
                break;
            }

            switch (grade){
                case "A+":
                value=4.0;
                valuetot=value*credit;
                break;

                case "A":
                value=3.7;
                valuetot=value*credit;
                break;

                case "B+":
                value=3.5;
                valuetot=value*credit;
                break;

                case "B":
                value=3.0;
                valuetot=value*credit;
                break;

                case "C+":
                value=2.5;
                valuetot=value*credit;
                break;

                case "C":
                value=2.0;
                valuetot=value*credit;
                break;

                case "C-":
                value=1.7;
                valuetot=value*credit;
                break;

                case "D+":
                value=1.5;
                valuetot=value*credit;
                break;

                case "D-":
                value=1.3;
                valuetot=value*credit;
                break;

                case "F":
                value=0;
                valuetot=value*credit;
                break;
            }
            tot=tot+valuetot;
            credittot=credittot+credit;
            GPA=tot/credittot;
            gpa.setText(String.valueOf(GPA));
        }
                 
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    private void subject(){
        try {
            pdst=con.connect().prepareStatement("select * from subject");
             ResultSet rs=pdst.executeQuery();
             subname.removeAllItems();
            
             while(rs.next()){
                 subname.addItem(rs.getString(3));
             }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(St_ca.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
     public String getdsubid(){
        
            String stid=id.getText();
            String sub=subname.getSelectedItem().toString();
            String subid="";
            String query1="select * from subject  where sub_name=?";
            try {
                pdst=con.connect().prepareStatement(query1);
                pdst.setString(1, sub);
            
            ResultSet rs=pdst.executeQuery();
            if(rs.next()==false){
                JOptionPane.showMessageDialog(this, "Not Valid Subject Number");
            }else{
                while(rs.next()){
                    subid=rs.getString("sub_id");
                }
            }
            } catch (SQLException ex) {
                Logger.getLogger(St_ca.class.getName()).log(Level.SEVERE, null, ex);
            }
            
       return subid;
    }
     
      public String get_text(String stid){ 
        stid=id.getText();
        //sub=sub_comb.getSelectedItem().toString();
        return stid;
        
   }
   public String get_text2(String sub){ 
        //stid=stid_txt.getText();
        sub=subname.getSelectedItem().toString();
        return sub;
        
   }
   
   
   private void getmarks(String stid,String sub){
       
        double theory= 0;
        double practical=0;
        String grade="";
        
        String subid="";
       
        
            
        String query1="select * from subject  where sub_name=?";
        try {
                pdst=con.connect().prepareStatement(query1);
                pdst.setString(1, sub);
            
            ResultSet rs=pdst.executeQuery();
            while(rs.next()){
                subid=rs.getString("sub_id");
            
            }
            String query2="select * from final_marks where sub_id=? and stu_id=?";
        
            pdst=con.connect().prepareStatement(query2);
             pdst.setString(1, subid); 
             pdst.setString(2, stid);
            
            rs=pdst.executeQuery();
            
            //get result for result set
            while(rs.next()){
                practical=rs.getDouble("practical");
                theory=rs.getDouble("theory");
                
                    
            
            //get full ca marks total
            double Finaltotal=(theory+practical)/2;
             // check CA pass or fail
            String CAStatus;
            
            double catotal=vc.getmarks(get_text(stid),get_text2(sub));
            System.out.println(catotal);
            
            if(catotal>=50){
                CAStatus="PASS";
            }
            else{
                 CAStatus = "FAIL";
            }
            
            double marks=(catotal+Finaltotal)/2;
            
            //calculate LecGrade
            if(CAStatus=="FAIL"){
               
                    grade="F";
            }
            else if(marks>=85){
                grade="A+";
            }
            else if(marks>=75){
                grade="A";
            }
            else if(marks>=70){
                grade="B+";
            }
            else if(marks>=65){
                grade="B";
            }
            else if(marks>=60){
                grade="C+";
            }
            else if(marks>=55){
                grade="C";
            }
            else if(marks>=50){
                grade="C-";
            }
            else if(marks>=45){
                grade="D+";
            }
             else if(marks>=35){
                grade="D-";
            }
            else{
                 grade="F";
             }
            
            
            tmodel=(DefaultTableModel)table.getModel();
                    tmodel.addRow(new Object[]{
                        stid,
                        subid,
                        CAStatus,
                        grade
                        
                    });
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(St_ca.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(st_grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(st_grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(st_grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(st_grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new st_grade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gpa;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> subname;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
