/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author admin
 */
public class StAttendance extends javax.swing.JFrame {

    Student stu = new Student();
    /**
     * Creates new form StAttendance
     */
    public StAttendance() {
        initComponents();
        showAtt2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        subid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Eligibility = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Attendance = new javax.swing.JLabel();
        Practical = new javax.swing.JLabel();
        AttCount = new javax.swing.JLabel();
        PraCount = new javax.swing.JLabel();
        Att = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        stid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Pra = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(84, 84, 84));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Attendance");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 210, 90));

        subid.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPanel1.add(subid, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 190, 30));

        table.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "date", "type", "title", "notice"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 590, 190));

        jButton2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton2.setText("Search");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Subject Code");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        Eligibility.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Eligibility.setForeground(new java.awt.Color(254, 254, 254));
        Eligibility.setText("Eligibility");
        jPanel1.add(Eligibility, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, -1, -1));

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setForeground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, -1, -1));

        Attendance.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Attendance.setForeground(new java.awt.Color(254, 254, 254));
        Attendance.setText("Attendance");
        jPanel1.add(Attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, -1, -1));

        Practical.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Practical.setForeground(new java.awt.Color(254, 254, 254));
        Practical.setText("Practical");
        jPanel1.add(Practical, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, -1, -1));

        AttCount.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        AttCount.setForeground(new java.awt.Color(248, 255, 66));
        jPanel1.add(AttCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, 150, 50));

        PraCount.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        PraCount.setForeground(new java.awt.Color(254, 253, 91));
        jPanel1.add(PraCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 610, 150, 50));

        Att.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Att.setForeground(new java.awt.Color(112, 254, 103));
        jPanel1.add(Att, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, 160, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/back.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, 70));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student Id");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 120, 30));

        stid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stidActionPerformed(evt);
            }
        });
        jPanel1.add(stid, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 190, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/background.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 1070, 830));

        Pra.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Pra.setForeground(new java.awt.Color(144, 254, 128));
        jPanel1.add(Pra, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 600, 170, 50));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 
        String sub=subid.getText();
        String id = stid.getText();
        if(!sub.equals("") && !id.equals("")){
            try {
                Connection con=DbConnect.connect();
                String sql="select * from attendance where stu_id='"+id+"' AND cu_id='"+sub+"'";
                PreparedStatement ps=con.prepareStatement(sql);
                ResultSet rs=ps.executeQuery();
                table.setModel(DbUtils.resultSetToTableModel(rs));
                table.setVisible(true);
                
                 if(sub.equals("TCS2112") || sub.equals("TCS2122"))
                {
                    eligibility_TCS();
                }else
                {
                    eligibility();
                }
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,"Please enter correct data!!!");
                table.setVisible(false);
            }
        }
        else
        {
            table.setVisible(false);
            JOptionPane.showMessageDialog(null,"Please enter subject code");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void stidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stidActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        welcome stu=new welcome();
        stu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    void eligibility(){
        
            eligibility ele=new eligibility();

            String sub = subid.getText();
            String id = stu.getRegno();

            float t = ele.getTheoryEligibility(id, sub);
            String countTh = String.format("%f", t);

            float p = ele.getPracticalEligibility(id, sub);
            String countPra = String.format("%f", p);

            ele.getTotalEligibility(id,sub);

            AttCount.setText(countTh);
            PraCount.setText(countPra);

            Att.setText(ele.getEligible(ele.getTheoryEligibility(id, sub)));
            Pra.setText(ele.getEligible(ele.getPracticalEligibility(id, sub)));  
        }
    
    void eligibility_TCS(){
        
            eligibility ele = new eligibility();

            String sub = subid.getText();
            String id = stu.getRegno();

            float t = ele.getTheoryEligibility(id, sub);
            String countTh = String.format("%f", t);

            ele.getTotalEligibility(id,sub);

            AttCount.setText(countTh);
            PraCount.setText("-");

            Att.setText(ele.getEligible(ele.getTheoryEligibility(id, sub)));
            Pra.setText("-");
  
        }
    
    void showAtt(){
        boolean flag = false;
        table.setVisible(flag);
    }
    
    void showAtt2()
    {
        Student stu = new Student();
        try {
            Connection con = MyConnection.getConnection();
            String sql = "select * from attendance where stu_id='"+stu.getRegno()+"'";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Att;
    private javax.swing.JLabel AttCount;
    private javax.swing.JLabel Attendance;
    private javax.swing.JLabel Eligibility;
    private javax.swing.JLabel Pra;
    private javax.swing.JLabel PraCount;
    private javax.swing.JLabel Practical;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField stid;
    private javax.swing.JTextField subid;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
