/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Lecturer.LecLogin;
import Student.StLogin;
import TechnicalOfficer.tecLogin;
import TechnicalOfficer.DeanLogin;
/**
 *
 * @author user
 */
public class forms_Login extends javax.swing.JFrame {

    /**
     * Creates new form forms_Login
     */
    public forms_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        admin = new javax.swing.JLabel();
        lecturer = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        student = new javax.swing.JLabel();
        techofficer = new javax.swing.JLabel();
        loginHome = new javax.swing.JLabel();
        techofficer2 = new javax.swing.JLabel();
        student2 = new javax.swing.JLabel();
        lecturer2 = new javax.swing.JLabel();
        admin2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255,30));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TechnicalOfficer/admin.png"))); // NOI18N
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
        });
        jPanel1.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 150, 130));

        lecturer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TechnicalOfficer/lecture.png"))); // NOI18N
        lecturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lecturerMouseClicked(evt);
            }
        });
        jPanel1.add(lecturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 140, 130));

        title.setFont(new java.awt.Font("Adobe Caslon Pro", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Login");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        student.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TechnicalOfficer/student.png"))); // NOI18N
        student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentMouseClicked(evt);
            }
        });
        jPanel1.add(student, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 130, 130));

        techofficer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TechnicalOfficer/technical.png"))); // NOI18N
        techofficer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                techofficerMouseClicked(evt);
            }
        });
        jPanel1.add(techofficer, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 150, 160));

        loginHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        loginHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginHomeMouseClicked(evt);
            }
        });
        jPanel1.add(loginHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, -1, -1));

        techofficer2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        techofficer2.setForeground(new java.awt.Color(255, 255, 255));
        techofficer2.setText("Technical Officer");
        techofficer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                techofficer2tecLogin(evt);
            }
        });
        jPanel1.add(techofficer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        student2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        student2.setForeground(new java.awt.Color(255, 255, 255));
        student2.setText("Student");
        jPanel1.add(student2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        lecturer2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lecturer2.setForeground(new java.awt.Color(255, 255, 255));
        lecturer2.setText("Lecturer");
        jPanel1.add(lecturer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        admin2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        admin2.setForeground(new java.awt.Color(255, 255, 255));
        admin2.setText("Admin");
        jPanel1.add(admin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TechnicalOfficer/background.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 840, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginHomeMouseClicked
        form_Home home=new form_Home();  // bck to the home
        home.setVisible(true);
        this.setVisible(false);     // TODO add your handling code here:
    }//GEN-LAST:event_loginHomeMouseClicked

    private void techofficer2tecLogin(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_techofficer2tecLogin
        tecLogin login = new tecLogin();

        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_techofficer2tecLogin

    private void techofficerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_techofficerMouseClicked
        tecLogin login = new tecLogin();

        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_techofficerMouseClicked

    private void studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentMouseClicked
        StLogin login = new StLogin();

        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_studentMouseClicked

    private void lecturerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturerMouseClicked
        LecLogin login = new LecLogin();

        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lecturerMouseClicked

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        form_Admin login = new form_Admin();

        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forms_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forms_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forms_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forms_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forms_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JLabel admin2;
    private javax.swing.JLabel background;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lecturer;
    private javax.swing.JLabel lecturer2;
    private javax.swing.JLabel loginHome;
    private javax.swing.JLabel student;
    private javax.swing.JLabel student2;
    private javax.swing.JLabel techofficer;
    private javax.swing.JLabel techofficer2;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
