/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lecturer;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class lec_ca extends javax.swing.JFrame {

    /**
     * Creates new form lec_ca
     */
    public lec_ca() {
        initComponents();
           subject();
    }

    
     PreparedStatement pdst;
     DbConnection con=new DbConnection();
     DefaultTableModel tmodel;

    String stid;
    String sub;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        subname = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CA Results");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 130, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lecturer/back.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 90, 80));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Subject");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 100, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 100, 30));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 200, 40));

        subname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(subname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 200, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lecturer/search.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 40, 40));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "student ID", "Subject Code", "quiz result", "assignment", "mid", "total CA", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 490, 90));

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 70, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lecturer/background.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       getmarks(get_text(stid),get_text2(sub));
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        LecGrade adm=new LecGrade();
         adm.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       for(int c=tmodel.getRowCount()-1;c>=0;c--){
                            tmodel.removeRow(c);
                        }
         
         //and clear the combo box and txtfield
         id.setText("");
         subname.setSelectedIndex(-1);
    }//GEN-LAST:event_jButton1ActionPerformed
  private void subject(){
        try {
            pdst=con.getConnection().prepareStatement("select * from subject");
             ResultSet rs=pdst.executeQuery();
             subname.removeAllItems();
            
             while(rs.next()){
                 subname.addItem(rs.getString(3));
             }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(lec_ca.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
   //get subject code from database
    public String getdsubid(){
        
            
            String subid="";
            String query1="select * from subject  where sub_name=?";
            try {
                pdst=con.getConnection().prepareStatement(query1);
                pdst.setString(1, sub);
            
            ResultSet rs=pdst.executeQuery();
            if(rs.next()==false){
                JOptionPane.showMessageDialog(this, "Not Valid Subject Number");
            }else{
                while(rs.next()){
                    subid=rs.getString("sub_id");
                }
            }
            } catch (SQLException ex) {
                Logger.getLogger(lec_ca.class.getName()).log(Level.SEVERE, null, ex);
            }
            
       return subid;
    }
   public String get_text(String stid){ 
        stid=id.getText();
        //sub=sub_comb.getSelectedItem().toString();
        return stid;
        
   }
   public String get_text2(String sub){ 
        //stid=stid_txt.getText();
        sub=subname.getSelectedItem().toString();
        return sub;
        
   }
   
  
    public double getmarks(String stid,String sub){
        
        String status = "";
        double total=0;
        
       // String stid=stid_txt.getText();
      //  String sub=sub_comb.getSelectedItem().toString();
        double q1 = 0;
        double q2=0;
        double q3=0;
        double q4=0;
        double ass1=0;
        double ass2=0;
        double ass3=0;
        double mid=0;
        String subid="";
       
        
            
        String query1="select * from subject  where sub_name=?";
        try {
                pdst=con.getConnection().prepareStatement(query1);
                pdst.setString(1, sub);
            
            ResultSet rs=pdst.executeQuery();
            while(rs.next()){
                subid=rs.getString("sub_id");
            
            }
            String query2="select * from ict_ca where sub_id=? and stu_id=?";
        
            pdst=con.getConnection().prepareStatement(query2);
            //caal to getsubid function
             pdst.setString(1, subid); 
             pdst.setString(2, stid);
            
            rs=pdst.executeQuery();
            
            //get result for result set
            while(rs.next()){
                q1=rs.getDouble("q1");
                q2=rs.getDouble("q2");
                q3=rs.getDouble("q3");
                q4=rs.getDouble("q4");
                ass1=rs.getDouble("ass1");
                ass2=rs.getDouble("ass2");
                ass3=rs.getDouble("ass3");
                mid=rs.getDouble("mid");
                        
            //assign quiz marks to array
            double[] quiz={q1,q2,q3,q4};
            double[] assignment={ass1,ass2,ass3};
            
            //get min value from quiz marks
            double min=quiz[0];
            double qtot=0;
            for(int i=0;i<4;i++){
                double no=quiz[i];
                if(min>no){
                    min=no;
                }
            }
            
            //get quiz total
            for(int j=0;j<4;j++){
                 if(min!=quiz[j]){
                     qtot= qtot  + quiz[j];
                }
            }
            
            //get assignment total
            double asstot=0;
             for(int c=0;c<3;c++){
                 
                     asstot= asstot  + assignment[c];
                
            }
            
            //get quiz marks
            double quiz_marks=qtot/3;
            double ass_marks=asstot/3;
            
            //get full ca marks total
            total=(quiz_marks+ass_marks+mid)/3;
            
            if(total>=50){
                status="PASS";
            }
            else{
                 status = "FAIL";
            }
            
            //new DecimalFormat("0.00").format(quiz_marks);
            
            
            tmodel=(DefaultTableModel)table.getModel();
                    tmodel.addRow(new Object[]{
                        stid,
                        subid,
                        quiz_marks,
                        ass_marks,
                        mid,
                        total,
                        status
                        
                    });
  
            }
        } catch (SQLException ex) {
            Logger.getLogger(lec_ca.class.getName()).log(Level.SEVERE, null, ex);
        }
        
             return total;  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lec_ca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lec_ca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lec_ca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lec_ca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lec_ca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> subname;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
