/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lecturer;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class LecMark extends javax.swing.JFrame {
            Connection con = null;
            ResultSet rs = null;
            PreparedStatement pst;
    /**
     * Creates new form ViewMarks
     */
    public LecMark() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        subid = new javax.swing.JTextField();
        stid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        practical = new javax.swing.JTextField();
        Q1 = new javax.swing.JTextField();
        Q2 = new javax.swing.JTextField();
        Q3 = new javax.swing.JTextField();
        Q4 = new javax.swing.JTextField();
        mid = new javax.swing.JTextField();
        Ass1 = new javax.swing.JTextField();
        Ass2 = new javax.swing.JTextField();
        Ass3 = new javax.swing.JTextField();
        theory = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lecturer/back.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 0, 100, 100);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Marks");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 30, 160, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("practical exam");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(480, 330, 90, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student ID");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 120, 90, 30);
        jPanel1.add(subid);
        subid.setBounds(230, 170, 150, 30);
        jPanel1.add(stid);
        stid.setBounds(230, 120, 150, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lecturer/search.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(440, 140, 50, 30);
        jPanel1.add(practical);
        practical.setBounds(480, 370, 80, 40);
        jPanel1.add(Q1);
        Q1.setBounds(30, 280, 80, 40);
        jPanel1.add(Q2);
        Q2.setBounds(140, 280, 80, 40);
        jPanel1.add(Q3);
        Q3.setBounds(250, 280, 80, 40);
        jPanel1.add(Q4);
        Q4.setBounds(370, 280, 80, 40);
        jPanel1.add(mid);
        mid.setBounds(480, 280, 80, 40);
        jPanel1.add(Ass1);
        Ass1.setBounds(20, 370, 80, 40);
        jPanel1.add(Ass2);
        Ass2.setBounds(140, 370, 80, 40);
        jPanel1.add(Ass3);
        Ass3.setBounds(250, 370, 80, 40);
        jPanel1.add(theory);
        theory.setBounds(370, 370, 80, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Subject ID");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 170, 90, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quiz 1");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 240, 90, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quiz 2");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(150, 240, 90, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Quiz 3");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(260, 240, 90, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Quiz 4");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(380, 240, 90, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("mid exam");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(490, 240, 90, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Assessment 1");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 330, 90, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Assessment 2");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(140, 330, 90, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Assessment 3");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(250, 330, 90, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Theory exam");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(370, 330, 90, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(370, 450, 100, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(130, 450, 100, 40);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lecturer/background.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(0, 0, 610, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       Lectrue lec = new  Lectrue ();
        lec.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        String id = stid.getText();
        String sub = subid.getText();
        
        LecMarks co = new LecMarks();

        if(!id.isEmpty() && !sub.isEmpty())
        {
            ResultSet rs = co.searchMarks(id,sub);
            try {
                if(rs.next())
                {
                    Q1.setText(rs.getString("q1"));
                    Q2.setText(rs.getString("q2"));  
                    Q3.setText(rs.getString("q3"));  
                    Q4.setText(rs.getString("q4"));
                    Ass1.setText(rs.getString("ass1"));
                    Ass2.setText(rs.getString("ass2"));
                    Ass3.setText(rs.getString("ass3"));
                    mid.setText(rs.getString("mid"));
                    theory.setText(rs.getString("theory"));
                    practical.setText(rs.getString("practical"));
                }
                else
                {
                    javax.swing.JOptionPane.showMessageDialog(null, "Data not in the database");
                    clear();
                }
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"error....");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please enter student id and subject id");
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LecMarks co = new LecMarks();

        co.setId(stid.getText());
        co.setSub(subid.getText());
        co.setQ1(Q1.getText());
        co.setQ2(Q2.getText());
        co.setQ3(Q3.getText());
        co.setQ4(Q4.getText());
        co.setA1(Ass1.getText());
        co.setA2(Ass2.getText());
        co.setA3(Ass3.getText());
        co.setMid(mid.getText());
        co.setPr(practical.getText());
        co.setTh(theory.getText());
        

        co.updateMarks();

        clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         LecMarks m = new LecMarks();


        String id = stid.getText().trim();
        String sub = subid.getText().trim();

        if(!sub.equals("") && !id.equals("")){
            try {
                m.setId(stid.getText());
                m.setSub(subid.getText());
                m.setQ1(Q1.getText());
                m.setQ2(Q2.getText());
                m.setQ3(Q3.getText());
                m.setQ4(Q4.getText());
                m.setA1(Ass1.getText());
                m.setA2(Ass2.getText());
                m.setA3(Ass3.getText());
                m.setMid(mid.getText());
                m.setTh(theory.getText());
                m.setPr(practical.getText());

                m.insert();
                clear();
            } 
            catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, e);
            }
        }
          else
          {
              javax.swing.JOptionPane.showMessageDialog(null, "Please enter Student ID and Subject ID ");
           }
    }//GEN-LAST:event_jButton1ActionPerformed
 public void clear(){
        stid.setText("");
        subid.setText("");
        Q1.setText("");
        Q2.setText("");
        Q3.setText("");
        Q4.setText("");
        Ass1.setText("");
        Ass2.setText("");
        Ass3.setText("");
        mid.setText("");
        theory.setText("");
        practical.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecMark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecMark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecMark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecMark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecMark().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ass1;
    private javax.swing.JTextField Ass2;
    private javax.swing.JTextField Ass3;
    private javax.swing.JTextField Q1;
    private javax.swing.JTextField Q2;
    private javax.swing.JTextField Q3;
    private javax.swing.JTextField Q4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mid;
    private javax.swing.JTextField practical;
    private javax.swing.JTextField stid;
    private javax.swing.JTextField subid;
    private javax.swing.JTextField theory;
    // End of variables declaration//GEN-END:variables
}
