/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lecturer;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class LecStudenteligibility extends javax.swing.JFrame {

    
    public LecStudenteligibility() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stid = new javax.swing.JTextField();
        subid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Theory = new javax.swing.JLabel();
        Eligibility = new javax.swing.JLabel();
        Practical = new javax.swing.JLabel();
        th = new javax.swing.JLabel();
        pra = new javax.swing.JLabel();
        thCount = new javax.swing.JLabel();
        praCount = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Eligibility");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 110, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Subject ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 110, 20));
        jPanel1.add(stid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 260, 30));
        jPanel1.add(subid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 260, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lecturer/back.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 100, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lecturer/search.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 50, 50));

        Theory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Theory.setForeground(new java.awt.Color(255, 255, 255));
        Theory.setText("Theory");
        jPanel1.add(Theory, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 100, 40));

        Eligibility.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Eligibility.setForeground(new java.awt.Color(255, 255, 255));
        Eligibility.setText("Eligibility");
        jPanel1.add(Eligibility, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 100, 40));

        Practical.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Practical.setForeground(new java.awt.Color(255, 255, 255));
        Practical.setText("Practical");
        jPanel1.add(Practical, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 100, 40));
        jPanel1.add(th, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, 10));
        jPanel1.add(pra, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));
        jPanel1.add(thCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));
        jPanel1.add(praCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lecturer/background.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
    Lectrue lc = new  Lectrue();
        lc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
      String id = stid.getText();
        String sub = subid.getText();
         
        if(!sub.equals("") && !id.equals("")){
            try {
                Connection con=DbConnection.getConnection();
                String sql="select * from attendances where stu_id='"+id+"' AND sub_id='"+sub+"'";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                
                if(!sub.equals("ICT1233"))
                {
                    eligibility();
                }
                
                 if(sub.equals("ICT1233"))
                {
                    eligibility_ICT();
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Please enter correct details!!!");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please both fields!!!");
        }
    }//GEN-LAST:event_jLabel5MouseClicked
void eligibility(){
        LecEligibility ele=new LecEligibility();
        
        String sub = subid.getText();
        String id = stid.getText();
        
        float t = ele.getTheoryEligibility(id, sub);
        String countTh = String.format("%f", t);
        
        float p = ele.getPracticalEligibility(id, sub);
        String countPra = String.format("%f", p);
        
        ele.getTotalEligibility(id,sub);
        
        thCount.setText(countTh);
        praCount.setText(countPra);
        
        th.setText(ele.getEligible(ele.getTheoryEligibility(id, sub)));
        pra.setText(ele.getEligible(ele.getPracticalEligibility(id, sub)));  
    }
    
    void eligibility_ICT(){
        LecEligibility ele = new LecEligibility();
        
        String sub = subid.getText();
        String id = stid.getText();
        
        float t = ele.getTheoryEligibility(id, sub);
        String countTh = String.format("%f", t);
        
        ele.getTotalEligibility(id,sub);
        
        thCount.setText(countTh);
        praCount.setText("-");
        
        th.setText(ele.getEligible(ele.getTheoryEligibility(id, sub)));
        pra.setText("-");
    } 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecStudenteligibility().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Eligibility;
    private javax.swing.JLabel Practical;
    private javax.swing.JLabel Theory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pra;
    private javax.swing.JLabel praCount;
    private javax.swing.JTextField stid;
    private javax.swing.JTextField subid;
    private javax.swing.JLabel th;
    private javax.swing.JLabel thCount;
    // End of variables declaration//GEN-END:variables
}
